# TODO:
#    o) does Hive successfully load jars from s3?
#    o) Glue data catalog

AWSTemplateFormatVersion: 2010-09-09
Description: "Create an EMR cluster with optionally spot task instances"

Parameters:
    ## Networking and access
    VPC:
        Type: AWS::EC2::VPC::Id
        Default: vpc-7f009219

    Subnet:
        Type: AWS::EC2::Subnet::Id
        Default: subnet-2e4f0975

    KeyPair:
        Type: AWS::EC2::KeyPair::KeyName
        Default: wwbrannon

    ## Instance types
    MasterInstanceType:
        Type: String
        Default: m4.large

    CoreInstanceType:
        Type: String
        Default: m4.large

    TaskInstanceType:
        Type: String
        Default: m4.large

    ## Instance counts and bounds
    InitialCoreSize:
        Type: Number
        Default: 1

    MaxCoreSize:
        Type: Number
        Default: 10

    InitialTaskSize:
        Type: Number
        Default: 1

    MaxTaskSize:
        Type: Number
        Default: 10
    
    ## Misc parameters
    CoreStorage:
        Type: Number
        Default: 100

    SpotPrice:
        Type: Number
        Default: 0.1 # or 0 for on-demand

    ExtraJarsLocation:
        Type: String
        Default: s3://cortico-public/hadoop-jar/

    ReleaseLabel:
        Type: String
        Default: emr-5.14.0

Conditions:
    WithSpotPrice:
        !Not [!Equals [0, !Ref SpotPrice]]

Resources:
    LogBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        Properties:
            AccessControl: Private

    SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: "Allow SSH from anywhere"
            VpcId: !Ref VPC
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0

    ServiceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Action: sts:AssumeRole
                      Principal:
                          Service:
                              - elasticmapreduce.amazonaws.com
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole
    
    JobFlowRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Action: sts:AssumeRole
                      Principal:
                          Service:
                              - ec2.amazonaws.com
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role
    
    AutoscalingRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Action: sts:AssumeRole
                      Principal:
                          Service:
                              - elasticmapreduce.amazonaws.com
                              - application-autoscaling.amazonaws.com
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforAutoScalingRole
    
    InstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Roles:
                - !Ref JobFlowRole
    
    Cluster:
        Type: AWS::EMR::Cluster
        Properties:
            Name: !Ref "AWS::StackName"
            ReleaseLabel: !Ref ReleaseLabel
            VisibleToAllUsers: true
            
            LogUri: !Sub
                - "s3://${bucket}/emr-logs/"
                - { bucket: !Ref LogBucket }

            Applications:
                - Name: Hadoop
                - Name: Ganglia
                - Name: Hive
                - Name: Spark
                - Name: Pig
                - Name: Hue

            AutoScalingRole: !Ref AutoscalingRole
            JobFlowRole: !Ref InstanceProfile
            ServiceRole: !Ref ServiceRole
            
            Configurations:
#                - Classification: spark-hive-site
#                  ConfigurationProperties:
#                      hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
#                - Classification: hive-site
#                  ConfigurationProperties:
#                      hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
                - Classification: yarn-site
                  ConfigurationProperties:
                      yarn.log-aggregation-enable: true
                      yarn.log-aggregation.retain-seconds: -1
                      yarn.nodemanager.remote-app-log-dir: !Sub
                          - "s3://${bucket}/aggregated-logs/"
                          - { bucket: !Ref LogBucket }

            Instances:
                TerminationProtected: false
                Ec2KeyName: !Ref KeyPair
                Ec2SubnetId: !Ref Subnet
                AdditionalMasterSecurityGroups:
                    - !Ref SecurityGroup
                
                MasterInstanceGroup:
                    InstanceCount: 1
                    InstanceType: !Ref MasterInstanceType
                    Market: ON_DEMAND
                    Name: MasterInstance

                CoreInstanceGroup:
                    InstanceCount: !Ref InitialCoreSize
                    InstanceType: !Ref CoreInstanceType
                    Market: ON_DEMAND
                    Name: CoreInstance
                    
                    EbsConfiguration:
                        EbsBlockDeviceConfigs:
                            - VolumeSpecification:
                                  SizeInGB: !Ref CoreStorage
                                  VolumeType: gp2
                              VolumesPerInstance: 1
                        EbsOptimized: true

                    AutoScalingPolicy:
                        Constraints:
                            MinCapacity: 1
                            MaxCapacity: !Ref MaxCoreSize
                        
                        Rules:
                            - Name: CoreNodeScaleOut
                              Description: "Core node scale-out based on HDFS utilization"
                              Action:
                                  SimpleScalingPolicyConfiguration:
                                      AdjustmentType: CHANGE_IN_CAPACITY
                                      ScalingAdjustment: 1
                                      CoolDown: 300
                              Trigger:
                                  CloudWatchAlarmDefinition:
                                      ComparisonOperator: GREATER_THAN
                                      EvaluationPeriods: 1
                                      MetricName: HDFSUtilization
                                      Namespace: AWS/ElasticMapReduce
                                      Period: 300
                                      Threshold: 80
                                      Statistic: AVERAGE
                                      Unit: PERCENT
                                      Dimensions:
                                          - Key: JobFlowId
                                            Value: "${emr.clusterId}"

    TaskInstanceGroupConfig:
        Type: AWS::EMR::InstanceGroupConfig
        Properties:
            Name: TaskInstance
            InstanceRole: TASK
            JobFlowId: !Ref Cluster
            InstanceCount: !Ref InitialTaskSize
            InstanceType: !Ref TaskInstanceType
            Market: !If [WithSpotPrice, SPOT, ON_DEMAND]
            BidPrice: !If [WithSpotPrice, !Ref SpotPrice, !Ref "AWS::NoValue"]
            
            Configurations:
#                - Classification: spark-hive-site
#                  ConfigurationProperties:
#                      hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
#                - Classification: hive-site
#                  ConfigurationProperties:
#                      hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
                - Classification: yarn-site
                  ConfigurationProperties:
                      yarn.log-aggregation-enable: true
                      yarn.log-aggregation.retain-seconds: -1
                      yarn.nodemanager.remote-app-log-dir: !Sub
                          - "s3://${bucket}/aggregated-logs/"
                          - { bucket: !Ref LogBucket }

            AutoScalingPolicy:
                Constraints:
                    MinCapacity: 1
                    MaxCapacity: !Ref MaxTaskSize
                Rules:
                    - Name: TaskNodeScaleOut
                      Description: "Task node scale-out based on memory utilization"
                      Action:
                          SimpleScalingPolicyConfiguration:
                              AdjustmentType: CHANGE_IN_CAPACITY
                              ScalingAdjustment: 1
                              CoolDown: 300
                      Trigger:
                          CloudWatchAlarmDefinition:
                              ComparisonOperator: LESS_THAN
                              EvaluationPeriods: 1
                              MetricName: YARNMemoryAvailablePercentage
                              Namespace: AWS/ElasticMapReduce
                              Period: 300
                              Threshold: 20
                              Statistic: AVERAGE
                              Unit: PERCENT
                              Dimensions:
                                  - Key: JobFlowId
                                    Value: "${emr.clusterId}"
                    
                    - Name: TaskNodeScaleIn
                      Description: "Task node scale-in based on memory utilization"
                      Action:
                          SimpleScalingPolicyConfiguration:
                              AdjustmentType: CHANGE_IN_CAPACITY
                              ScalingAdjustment: -1
                              CoolDown: 300
                      Trigger:
                          CloudWatchAlarmDefinition:
                              ComparisonOperator: GREATER_THAN
                              EvaluationPeriods: 1
                              MetricName: YARNMemoryAvailablePercentage
                              Namespace: AWS/ElasticMapReduce
                              Period: 300
                              Threshold: 75
                              Statistic: AVERAGE
                              Unit: PERCENT
                              Dimensions:
                                  - Key: JobFlowId
                                    Value: "${emr.clusterId}"

    DebugSetupStep:
        Type: AWS::EMR::Step
        Properties:
            Name: SetupDebuggingTool
            ActionOnFailure: CONTINUE
            JobFlowId: !Ref Cluster
            HadoopJarStep:
                Jar: "command-runner.jar"
                Args:
                    - 'state-pusher-script'

Outputs:
    Cluster:
        Description: EMR Cluster DNS
        Value: !GetAtt Cluster.MasterPublicDNS

