name: sparkenv
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7.0
  - pip
  - pip:
    - num2words
    - torchtext
    - bloom-filter
    - torchviz
    - spark_sklearn
  - basemap
  - beautifulsoup4
  - blas
  - boto
  - boto3
  - botocore
  - cudatoolkit
  - cudnn
  - curl
  - fiona
  - future
  - gdal
  - gensim
  - geopandas
  - geos
  - h5py
  - hdbscan
  - hdf4
  - hdf5
  - icu
  - idna
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jinja2
  - joblib
  - json-c
  - jsonschema
  - jupyter_client
  - jupyter_core
  - keras
  - keras-applications
  - keras-base
  - keras-preprocessing
  - krb5
  - markdown
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl_fft
  - mkl_random
  - mkl-service
  - mock
  - more-itertools
  - mysqlclient
  - mysql-connector-c
  - nbconvert
  - nbformat
  - networkx
  - nltk
  - numpy
  - pandas
  - pandasql
  - pandoc
  - pandocfilters
  - patsy
  - pattern
  - pcre
  - pip
  - plotly
  - protobuf
  - psycopg2
  - pygments
  - pyparsing
  - pyshp
  - pyspark
  - python-dateutil
  - python-docx
  - python-louvain
  - pytorch
  - pytz
  - pyyaml
  - readline
  - regex
  - requests
  - s3transfer
  - s3contents
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - shapely
  - simplejson
  - six
  - spacy
  - sparkmagic
  - sqlalchemy
  - sqlite
  - statsmodels
  - torchvision
  - tqdm
  - urllib3
  - webencodings
  - widgetsnbextension
  - wheel
  - wordcloud
  - yaml

