name: sparkenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.0

  # packages via pip
  - pip
  - pip:
    - num2words
    - bloom-filter
    - spark_sklearn
    #- torchtext
    #- torchviz

  # large deep learning packages via conda
  #- cudatoolkit
  #- cudnn
  #- pytorch
  #- torchvision
  #- keras
  #- keras-applications
  #- keras-base
  #- keras-preprocessing

  # other packages via conda
  - basemap
  - beautifulsoup4
  - blas
  - boto
  - boto3
  - botocore
  - curl
  - fiona
  - future
  - gdal
  - gensim
  - geopandas
  - geos
  - h5py
  - hdbscan
  - hdf4
  - hdf5
  - icu
  - idna
  - ipykernel
  - ipython
  - ipython_genutils
  - jinja2
  - joblib
  - json-c
  - jsonschema
  - jupyter_client
  - jupyter_core
  - krb5
  - markdown
  - matplotlib
  - matplotlib-base
  - nbconvert
  - nbformat
  - networkx
  - nltk
  - numpy
  - pandas
  - pandasql
  - pandoc
  - pandocfilters
  - patsy
  - pcre
  - plotly
  - protobuf
  - psycopg2
  - pygments
  - pyparsing
  - pyshp
  - pyspark
  - python-dateutil
  - python-docx
  - python-louvain
  - pytz
  - pyyaml
  - readline
  - regex
  - requests
  - s3transfer
  - s3contents
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - shapely
  - simplejson
  - six
  - spacy
  - sparkmagic
  - sqlalchemy
  - sqlite
  - statsmodels
  - tqdm
  - urllib3
  - webencodings
  - widgetsnbextension
  - wheel
  - wordcloud
  - yaml

