name: sparkenv
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - pip
  - pip:
    - num2words
    - torchtext
    - bloom-filter
    - torchviz
    - docopt
    - en-core-web-lg
    - en-core-web-md
    - en-core-web-sm
    - en-vectors-web-lg
  - absl-py
  - asn1crypto
  - astor
  - attrs
  - backcall
  - backports
  - backports.csv
  - backports.functools_lru_cache
  - basemap
  - beautifulsoup4
  - blas
  - bleach
  - boto
  - boto3
  - botocore
  - bz2file
  - bzip2
  - ca-certificates
  - cairo
  - c-ares
  - certifi
  - cffi
  - chardet
  - cheroot
  - cherrypy
  - click
  - click-plugins
  - cligj
  - cryptography
  - cudatoolkit
  - cudnn
  - curl
  - cycler
  - cymem
  - cytoolz
  - dbus
  - decorator
  - defusedxml
  - descartes
  - dill
  - docutils
  - entrypoints
  - expat
  - feedparser
  - fiona
  - fontconfig
  - freetype
  - freexl
  - future
  - gast
  - gdal
  - gensim
  - geopandas
  - geos
  - giflib
  - glib
  - gmp
  - grpcio
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdbscan
  - hdf4
  - hdf5
  - icu
  - idna
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jaraco.functools
  - jedi
  - jinja2
  - jmespath
  - joblib
  - jpeg
  - json-c
  - jsonschema
  - jupyter_client
  - jupyter_core
  - kealib
  - keras
  - keras-applications
  - keras-base
  - keras-preprocessing
  - kiwisolver
  - krb5
  - libboost
  - libcurl
  - libdap4
  - libedit
  - libffi
  - libgcc-ng
  - libgdal
  - libgfortran-ng
  - libkml
  - libnetcdf
  - libpng
  - libpq
  - libprotobuf
  - libsodium
  - libspatialindex
  - libspatialite
  - libssh2
  - libstdcxx-ng
  - libsvm
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - libxslt
  - lxml
  - mapclassify
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - mkl_fft
  - mkl_random
  - mkl-service
  - mock
  - more-itertools
  - msgpack-numpy
  - msgpack-python
  - munch
  - murmurhash
  - mysqlclient
  - mysql-connector-c
  - nbconvert
  - nbformat
  - ncurses
  - networkx
  - ninja
  - nltk
  - numpy
  - numpy-base
  - olefile
  - openjpeg
  - openssl
  - pandas
  - pandasql
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pattern
  - pcre
  - pdfminer.six
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - plac
  - plotly
  - poppler
  - poppler-data
  - portend
  - preshed
  - proj4
  - prompt_toolkit
  - protobuf
  - psycopg2
  - ptyprocess
  - pycparser
  - pycryptodome
  - pygments
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyrsistent
  - pyshp
  - pysocks
  - pyspark
  - python
  - python-dateutil
  - python-docx
  - python-louvain
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - readline
  - regex
  - repoze.lru
  - requests
  - retrying
  - routes
  - rtree
  - s3transfer
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - shapely
  - simplejson
  - sip
  - six
  - smart_open
  - sortedcontainers
  - soupsieve
  - spacy
  - sparkmagic
  - sqlalchemy
  - sqlite
  - statsmodels
  - tempora
  - tensorboard
  - tensorflow
  - tensorflow-estimator
  - tensorflow-gpu
  - termcolor
  - testpath
  - thinc
  - tk
  - toolz
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - ujson
  - urllib3
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - wordcloud
  - wrapt
  - xerces-c
  - xz
  - yaml
  - zc.lockfile
  - zeromq
  - zlib
  - zstd

